#!/usr/bin/env python
# -*- coding: utf-8 -*-
from os import path
import sys

from tests.test_helpers import StoryscriptHubFixture


sys.path.insert(0, path.dirname(path.dirname(path.realpath(__file__))))

services = [
    'Arinono/microservice-validate',
    'awesome',
    'gmaps',
    'http',
    'kennethreitz/uritool',
    'log',
    'mailgun',
    'random',
    'sendgrid',
    'slack',
    'twitter',
    'uuid',
    'yaml'
]

StoryscriptHubFixture.update_hub_fixtures(services)
