#!/usr/bin/env python
# -*- coding: utf-8 -*-
from os import path
import sys

from storyhub.sdk.ServiceWrapper import ServiceWrapper


services = [
    'Arinono/microservice-validate',
    'awesome',
    'gmaps',
    'http',
    'kennethreitz/uritool',
    'log',
    'mailgun',
    'random',
    'redis',
    'sendgrid',
    'slack',
    'twitter',
    'uuid',
    'yaml'
]

hub_fixtures_file = path.join(path.dirname(path.realpath(__file__)),
                              'hub_fixture.json.fixed')

ServiceWrapper(services).as_json_file(hub_fixtures_file)
